- name: Deploy Application
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run App Container
      docker_container:
        name: lab8_ansible_app
        image: nginx:latest
        ports:
          - "8087:80"
        state: started