- name: Deploy Containerized App
  hosts: webservers
  become: yes
  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Application Container
      docker_container:
        name: lab7_ansible_nginx
        image: nginx:latest
        ports:
          - "8085:80"
        state: started
